// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGyUFptYRvUvdGaCqjsMEjwC71QynFCzE',
    appId: '1:1008685749737:web:d8f03122921680de45a778',
    messagingSenderId: '1008685749737',
    projectId: 'flutterpractice-b48fc',
    authDomain: 'flutterpractice-b48fc.firebaseapp.com',
    storageBucket: 'flutterpractice-b48fc.appspot.com',
    measurementId: 'G-7RMRWYS3D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4QJC0b2Y-o17DEmxhaMxfjj2mJgJR0do',
    appId: '1:1008685749737:android:725fa7dcb9bd24b545a778',
    messagingSenderId: '1008685749737',
    projectId: 'flutterpractice-b48fc',
    storageBucket: 'flutterpractice-b48fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiZP37zBnoThT91LIO6pxZGydORTPSkyQ',
    appId: '1:1008685749737:ios:6a98da16630b614445a778',
    messagingSenderId: '1008685749737',
    projectId: 'flutterpractice-b48fc',
    storageBucket: 'flutterpractice-b48fc.appspot.com',
    iosBundleId: 'com.devonaya.flutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiZP37zBnoThT91LIO6pxZGydORTPSkyQ',
    appId: '1:1008685749737:ios:9803731e48e28cd545a778',
    messagingSenderId: '1008685749737',
    projectId: 'flutterpractice-b48fc',
    storageBucket: 'flutterpractice-b48fc.appspot.com',
    iosBundleId: 'com.example.flutterPractice.RunnerTests',
  );
}
